fullname: Alexey Konstantinov
favicon: /assets/images/favicon.svg
logo: /assets/images/photo.jpg

show_info: true
age: 21 y.o.
location: Sirius, Russia
language: Russian, English

show_contacts: true
mailto: mailto:konstantinov.py@gmail.com
cv_pdf_link: https://raw.githubusercontent.com/AwesomeAlexey/AwesomeAlexey.github.io/main/pdf/Konstantinov_Alexey.pdf

remote_theme: annndruha/minimal-resume
plugins:
- jekyll-remote-theme
